server:
  port: 8085
management:
  security:
    enabled: false


##在启动时要注意，有时候明明这里没指定端口号或者指定了端口号，和没有配置server-context-path项目访问地址，
##但是启动后发现端口号不对，还有项目访问地址或者其他配置不对，那是因为bootstrap.yml里调了config-server的服务读取了父上下文的配置文件，
##刚好父配置文件里也指了端口号和context-path,且父上下文没有将配置设置为可覆盖，因此在启动时要注意这个问题

#测试http://localhost:8084/profile或http://localhost:8084/getDatasource指向ConfigClientController的方法，访问得到数据则成功


#很多时候，需要在运行期间动态调整配置，可使用/refresh端点手动刷新配置。actuator的依赖包含了/refresh端点。
#在Controller上添加注解@RefreshScope。
#配置后要手动做一次刷新，否则不起作用，如http://localhost:8084/refresh,一定要用post方式去刷新