server:
  port: 8761
eureka:
  client:
    #是否将自己注册到eureka server中，默认为true,由于本身就是server,所以不用
    register-with-eureka: false
    #是否从eureak server获取注册信息，默认为true, 因为是单点server不用从其他eureka server复制节点数据，所以设置为false
    fetch-registry: false
    #Eureka server交互地址，查询服务和注册服务都依赖这个地址
    service-url:
          defaultZone: http://localhost:${server.port}/eureka/
  instance:
    hostname: localhost


  #由于本地调试很容易触发注册中心的保护机制，这会使得注册中心维护的服务实例不那么准确。所以，我们在本地进行开发的时候，
  #可以使用eureka.server.enable-self-preservation=false参数来关闭保护机制，以确保注册中心将不可用的实例正确剔除
  #更改Eureka更新频率将打破服务器的自我保护功能，生产环境下不建议自定义这些配置
  server:
    enable-self-preservation: false # 设为false，关闭自我保护，生产环境下不建议
    # 清理间隔（单位毫秒，默认是60*1000）
    interval-timer-in-ms: 1000
